//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiggWhaleWebAppDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundAsset
    {
        public string id { get; set; }
        public string fund_id { get; set; }
        public Nullable<System.DateTime> Total_Net_Assets_Date { get; set; }
        public string Total_Net_Assets { get; set; }
        public string Quality { get; set; }
        public Nullable<System.DateTime> Crawl_Date { get; set; }
        public Nullable<System.DateTime> Top_Funds_Date1 { get; set; }
        public string Top_Funds1 { get; set; }
        public string Total_Net_Assets1 { get; set; }
        public Nullable<System.DateTime> Quality_Date1 { get; set; }
        public Nullable<System.DateTime> Crawl_Date1 { get; set; }
    
        public virtual Fund Fund { get; set; }
    }
}
