//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiggWhaleWebAppDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fund
    {
        public Fund()
        {
            this.FundAssets = new HashSet<FundAsset>();
            this.FundDetails = new HashSet<FundDetail>();
        }
    
        public string id { get; set; }
        public string Name { get; set; }
        public string Fund_Type { get; set; }
        public string Ticker_Symbol { get; set; }
        public string Asset_Class { get; set; }
        public Nullable<System.DateTime> Inception_Date { get; set; }
        public string Advisor { get; set; }
        public string Manager_And_Tenure { get; set; }
        public string Phone { get; set; }
        public string Website { get; set; }
        public Nullable<decimal> Total_Net_Assets { get; set; }
        public Nullable<System.DateTime> Total_Net_Assets_Date { get; set; }
        public Nullable<decimal> Percent_Leveraged_Assets { get; set; }
        public Nullable<System.DateTime> Percent_Leveraged_Assets_Date { get; set; }
        public Nullable<decimal> Portfolio_Turnover { get; set; }
        public Nullable<decimal> Management_Fees { get; set; }
        public Nullable<decimal> Expense_Ratio { get; set; }
        public Nullable<decimal> Alternative_Minimum_Tax { get; set; }
        public string Fund_Objective { get; set; }
        public Nullable<decimal> Yield { get; set; }
        public string Fund_Type1 { get; set; }
        public string Ticker_Symbol1 { get; set; }
        public string Asset_Class1 { get; set; }
        public Nullable<System.DateTime> Inception_Date1 { get; set; }
        public string Manager_And_Tenure1 { get; set; }
        public Nullable<decimal> Total_Net_Assets1 { get; set; }
        public Nullable<System.DateTime> Total_Net_Assets_Date1 { get; set; }
        public Nullable<decimal> Percent_Leveraged_Assets1 { get; set; }
        public Nullable<System.DateTime> Percent_Leveraged_Assets_Date1 { get; set; }
        public Nullable<decimal> Portfolio_Turnover1 { get; set; }
        public Nullable<decimal> Management_Fees1 { get; set; }
        public Nullable<decimal> Expense_Ratio1 { get; set; }
        public Nullable<decimal> Alternative_Minimum_Tax1 { get; set; }
        public string Fund_Objective1 { get; set; }
    
        public virtual ICollection<FundAsset> FundAssets { get; set; }
        public virtual ICollection<FundDetail> FundDetails { get; set; }
    }
}
