//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiggWhaleWebAppDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundDetail
    {
        public string id { get; set; }
        public string fund_id { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Crawl_Date { get; set; }
        public Nullable<decimal> OneYearLipperAvg { get; set; }
        public Nullable<decimal> TenYearMarketReturn { get; set; }
        public Nullable<decimal> FiveYearMarketReturn { get; set; }
        public Nullable<decimal> OneYearMarketReturn { get; set; }
        public Nullable<decimal> YTDMarketReturn { get; set; }
        public Nullable<int> TenYearMarketReturnRank { get; set; }
        public Nullable<int> FiveYearMarketReturnRank { get; set; }
        public Nullable<int> OneYearMarketReturnRank { get; set; }
        public Nullable<int> YTDMarketReturnRank { get; set; }
        public Nullable<decimal> TenYearNAVReturn { get; set; }
        public Nullable<decimal> FiveYearNAVReturn { get; set; }
        public Nullable<decimal> OneYearNAVReturn { get; set; }
        public Nullable<decimal> YTDNAVReturn { get; set; }
        public Nullable<int> TenYearNAVReturnRank { get; set; }
        public Nullable<int> FiveYearNAVReturnRank { get; set; }
        public Nullable<int> OneYearNAVReturnRank { get; set; }
        public Nullable<int> YTDNAVReturnRank { get; set; }
        public Nullable<decimal> TenYearPremiumDiscountAvg { get; set; }
        public Nullable<decimal> FiveYearPremiumDiscountAvg { get; set; }
        public Nullable<decimal> YTDPremiumDiscountAvg { get; set; }
        public Nullable<decimal> NAV { get; set; }
        public Nullable<decimal> MarketPrice { get; set; }
        public Nullable<decimal> NetChange { get; set; }
        public Nullable<decimal> MarketChange { get; set; }
        public Nullable<decimal> OneYearNAVReturnAct { get; set; }
        public Nullable<System.DateTime> TwelveMonthYieldDate { get; set; }
        public Nullable<decimal> DefinedIncomeOnlyYield { get; set; }
        public Nullable<decimal> DistributionYield { get; set; }
        public Nullable<decimal> MostRecentIncimeDividend { get; set; }
        public Nullable<decimal> MostRecentIncomeDividendDate { get; set; }
        public Nullable<decimal> MostRecentCapGainDiviednd { get; set; }
        public Nullable<decimal> MostRecentCapGainDividendDate { get; set; }
        public Nullable<decimal> MonthlyYTDDividends { get; set; }
        public Nullable<decimal> YTDCapGains { get; set; }
        public Nullable<decimal> PremiumDiscount { get; set; }
        public Nullable<System.DateTime> Create_Date1 { get; set; }
        public string Created_By1 { get; set; }
        public Nullable<System.DateTime> Crawl_Date1 { get; set; }
    
        public virtual Fund Fund { get; set; }
    }
}
