//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiggWhaleWebAppDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public string id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Last_Crawl { get; set; }
        public string Url { get; set; }
        public string Created_By1 { get; set; }
        public Nullable<System.DateTime> Last_Crawl1 { get; set; }
    }
}
