//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiggWhaleWebAppDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SummaryData
    {
        public string id { get; set; }
        public string Fund_Name { get; set; }
        public string Ticker_Symbol { get; set; }
        public Nullable<System.DateTime> Summary_Date { get; set; }
        public string Calculated_Stat { get; set; }
        public Nullable<decimal> Calculated_Value { get; set; }
        public Nullable<int> RankOrder { get; set; }
        public string Data_Source { get; set; }
    }
}
