//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiggWhaleWebAppDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> lastmodified { get; set; }
        public Nullable<bool> enabled { get; set; }
        public Nullable<bool> passwordexpired { get; set; }
        public Nullable<System.DateTime> passwordchangedate { get; set; }
        public Nullable<short> passwordminlength { get; set; }
        public Nullable<bool> passwordneverexpires { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid ApplicationId { get; set; }
        public Nullable<bool> IsAnonymous { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
    }
}
